[package]
name = "encrypted-text"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.22.1"
pkcs8 = { version = "0.10.2", features = ["pem"] }
rand_core = "0.6.4"
rsa = { version = "0.9.8", features = ["pem"] }
