[package]
name = "fcgi-app"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
fastcgi = "1.0.0"
log = "0.4.20"
env_logger = "0.10.1"
libc = "0.2"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
http = "0.2"
